version: '3'
services:
  dscp-node:
    image: digicatapult/dscp-node:v4.3.1
    command: --base-path /data/
      --dev
      --unsafe-ws-external
      --unsafe-rpc-external
      --rpc-cors all
    ports:
      - 30333:30333
      - 9944:9944
      - 9933:9933
    restart: on-failure
