version: '3'
services:
  sqnc-node:
    image: digicatapult/sqnc-node:v12.5.1
    command: --base-path /data/
      --dev
      --unsafe-rpc-external
      --rpc-cors all
    ports:
      - 30333:30333
      - 9944:9944
      - 9933:9933
    restart: on-failure
