name: Release (NPM)
on:
  push:
    branches: ['main']
jobs:
  static-checks-npm:
    uses: digicatapult/shared-workflows/.github/workflows/static-checks-npm.yml@main
    with:
      matrix_commands: '["lint", "depcheck", "check"]'
  check-version:
    uses: digicatapult/shared-workflows/.github/workflows/check-version.yml@main
    permissions:
      contents: write
  tests-npm:
    uses: digicatapult/shared-workflows/.github/workflows/tests-npm.yml@main
    with:
      tests: '["test", "test:unit"]'
      docker_compose_file: ''
  release-npm:
    needs: [static-checks-npm, tests-npm]
    uses: digicatapult/shared-workflows/.github/workflows/release-module-npm.yml@main
    with:
      npm_build: true
    permissions:
      contents: write
    secrets:
      REGISTRY_AUTH_TOKEN: ${{ secrets.NPMJS_TOKEN }}
  release-gh-packages:
    needs: [static-checks-npm, tests-npm]
    uses: digicatapult/shared-workflows/.github/workflows/release-module-npm.yml@main
    with:
      npm_build: true
      registry_url: 'https://npm.pkg.github.com'
    permissions:
      contents: write
    secrets:
      REGISTRY_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  release-github:
    needs: [release-npm, release-gh-packages]
    uses: digicatapult/shared-workflows/.github/workflows/release-github.yml@main
    permissions:
      contents: write
      pull-requests: read
    secrets: inherit
